---
# vars file for aws-sg-whitelist-my-ip

security_groups:
  - name: sg_1_name
    vpc_id: vpc_id
    rules:
    - proto: tcp
      from_port: 80
      to_port: 80
      cidr_ip: "{{my_ip}}"
    - proto: tcp
      from_port: 443
      to_port: 443
      cidr_ip: "{{my_ip}}"
  - name: sg_2_name
    vpc_id: vpc_id
    rules:
    - proto: udp
      from_port: 123
      to_port: 123
      cidr_ip: "{{my_ip}}"
    - proto: tcp
      from_port: 0
      to_port: 65535
      cidr_ip: "{{my_ip}}"
    - proto: all
      cidr_ip: "{{my_ip}}"
