- name: Get previous security_group files
  find: paths="{{path_to_role}}/files"  patterns="sg_*.json"
  register: find_output

- set_fact:
    backed_up_sg_file_paths: "{{find_output.files|map(attribute='path')|list}}"

- command: "cat {{item}}"
  with_items: "{{backed_up_sg_file_paths}}"
  register: backed_up_sg_file_output

- set_fact:
    backed_up_security_groups: "{{backed_up_sg_file_output.results|map(attribute='stdout')|list}}"

- name: Set security group rules to original values
  include: set_security_groups_to_original_rules.yml
  with_items: "{{backed_up_security_groups}}"

- name: Delete previously backed up security_group files
  file: path="{{item}}" state=absent
  with_items: "{{backed_up_sg_file_paths}}"